# Generated by Django 4.2.7 on 2023-11-11 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brags', '0003_remove_company_owner_delete_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brag',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brags.category'),
        ),
    ]
