# Generated by Django 4.2.7 on 2023-11-14 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brags', '0005_company_category_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brag',
            name='extra_link',
        ),
        migrations.RemoveField(
            model_name='brag',
            name='status',
        ),
        migrations.AlterField(
            model_name='brag',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brags.category'),
            preserve_default=False,
        ),
    ]
